# Generated by Django 4.2.11 on 2024-05-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoctorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='user_photos/'),
        ),
    ]
