# Generated by Django 4.2.11 on 2024-05-01 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoctorApp', '0006_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='day',
        ),
        migrations.AddField(
            model_name='availability',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
