# Generated by Django 4.2.11 on 2024-05-30 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoctorApp', '0007_remove_availability_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyDoctorApp.availability'),
        ),
        migrations.AddField(
            model_name='availability',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
