# Generated by Django 4.2.11 on 2024-06-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoctorApp', '0010_user_saved_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
