# Generated by Django 4.2.11 on 2024-06-18 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoctorApp', '0011_remove_message_chat_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_availability', to='MyDoctorApp.appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='MyDoctorApp.availability'),
        ),
    ]
