# Generated by Django 4.2.11 on 2024-07-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoctorApp', '0014_remove_availability_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='missed_appointments',
        ),
    ]
