# Generated by Django 4.2.11 on 2024-07-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoctorApp', '0015_remove_user_missed_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='missed_appointments',
            field=models.IntegerField(default=0),
        ),
    ]
