# Generated by Django 4.2.11 on 2024-07-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoctorApp', '0016_user_missed_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='note',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Canceled', 'Canceled'), ('Completed', 'Completed'), ('Patient Absent', 'Patient Absent')], default='Booked', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='user_photos/default.png', upload_to='user_photos/'),
        ),
        migrations.DeleteModel(
            name='Blacklist',
        ),
    ]
