# Generated by Django 4.2.11 on 2024-07-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoctorApp', '0017_remove_appointment_note_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
