# Generated by Django 4.2.11 on 2024-07-19 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoctorApp', '0018_remove_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='MyDoctorApp.availability'),
        ),
    ]
