# Generated by Django 4.2.11 on 2024-07-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoctorApp', '0019_alter_appointment_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='user_photos/default.png', upload_to='./user_photos/'),
        ),
    ]
