# Generated by Django 4.2.11 on 2024-07-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoctorApp', '0020_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='user_photos/default.png', upload_to='MyDoctorApp/user_photos/'),
        ),
    ]
