# Generated by Django 4.2.11 on 2024-03-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing_comment_bid_user_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='starting_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
