# Generated by Django 4.2.11 on 2024-03-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='isActive',
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('sold', 'Sold')], default='active', max_length=10),
        ),
    ]
